# An incomplete identity block
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?item ?itemLabel ?missing
WHERE {
  ?item wdt:P31 wd:Q141115627 .
  {
    FILTER NOT EXISTS { ?item wdt:P6104 wd:Q141169143 . }
    BIND("P6104 WikiProject" AS ?missing)
  } UNION {
    FILTER NOT EXISTS { ?item wdt:P361 wd:Q141190255 . }
    BIND("P361 open-archaeo" AS ?missing)
  } UNION {
    FILTER NOT EXISTS { ?item wdt:P361 wd:Q141115774 . }
    BIND("P361 chublets.software" AS ?missing)
  } UNION {
    FILTER NOT EXISTS { ?item wdt:P195 wd:Q141190255 . }
    BIND("P195 collection" AS ?missing)
  } UNION {
    FILTER NOT EXISTS {
      ?item p:P217 [ pq:P195 wd:Q141190255 ] .
    }
    BIND("P217 slug" AS ?missing)
  } UNION {
    FILTER NOT EXISTS { ?item wdt:P2888 ?url . }
    BIND("P2888 entry URL" AS ?missing)
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de". }
}
ORDER BY ?missing ?itemLabel
