# Repositories with an archived snapshot
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?item ?itemLabel ?repo ?archive ?archiveDate
WHERE {
  ?item wdt:P31 wd:Q141115627 ;
        wdt:P6104 wd:Q141169143 ;
        p:P1324 ?statement .
  ?statement ps:P1324 ?repo ;
             pq:P1065 ?archive .
  OPTIONAL { ?statement pq:P2960 ?archiveDate . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de". }
}
ORDER BY DESC(?archiveDate)
